### ISSUE TITLE
csv_1d_to_2d: Axis ticks

### ISSUE THREAD

**Issue by realspacekolle** [maak-sdu/pyScattData#1]
In the plots generated: On the horizontal axis (x-axis) there are tick marks for every two mm, but on the vertical axis (y-axis) there are ticks for each mm. Please be coherent ;-)

**Comment by maak-sdu** [comment]
Thanks for the request, @realspacekolle. Please pull the latest updates from main, run the code, check whether your request has been met, and report back here. Thanks!
