### ISSUE TITLE
merging all data from a h5 file

### ISSUE THREAD

**Issue by realspacekolle** [maak-sdu/pyScattData#3]
It seems that I cannot merge all scans from a h5 file with the h5_extract_wrote_plot code

`        File: LNMO_p8_scan-0000.h5
                Number of scans: 21
                Do you want to merge any of the scans? (y/n): y
                Do you want to write .xy files for all merged scans? (y/n): y
                Do you want to plot all merged scans? (y/n): y
                        How many scans should be stacked together?: 21
                Writing to two-column files of merged scans...
                        00-20
Traceback (most recent call last):
  File "h5_extract_write_plot.py", line 296, in <module>
    main()
  File "h5_extract_write_plot.py", line 276, in main
    dict_to_xy_write(d_merged, fname)
  File "h5_extract_write_plot.py", line 59, in dict_to_xy_write
    x, y = twotheta, intensity[i,:]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

In this case I have a number of h5 files, one for each scan in an operando series. Each of these scans then contain 21 "subscans" that I want to merge to one scan.

**Comment by maak-sdu** [comment]
@realspacekolle: please pull the latest updates and test, whether the issue has been fixed. If so, please close this issue. If not, please report back here. Thanks.

**Comment by realspacekolle** [comment]
It is fixed.
