### ISSUE TITLE
h5_merge_all_write_plot: X-axis flipped(?)

### ISSUE THREAD

**Issue by realspacekolle** [maak-sdu/pyScattData#4]
Just tested this new version of the h5 extractor. It works fine for this type of data sets.
It seams the the X-axis (2theta for the example data) is flipped somehow. The peaks has lower intensities towards the top of the plot but the x-axis indicate this is smaller angles where the peaks with highest intensities are expected.

**Comment by maak-sdu** [comment]
@realspacekolle: the intensity matrix is now flipped such that it matches the axis ticks. Please pull the latest version and test if the issue has been fixed. If so, please close the issue here. If not, please report back here. Thanks.
