### ISSUE TITLE
scattdata_esd_normalize_bkgsub: nan for .xye files

### ISSUE THREAD

**Issue by bpandersen** [maak-sdu/pyScattData#6]
[N2_BPA-LVP-pm1-p7_scan_001.zip](https://github.com/maak-sdu/pyScattData/files/11077573/N2_BPA-LVP-pm1-p7_scan_001.zip)

**Comment by maak-sdu** [comment]
@bpandersen realized that many esds are reported as nan.

**Comment by maak-sdu** [comment]
bug solved. The cause was use of x-array (q[Å^-1, q[nm^-1], 2theta[deg]) rather than 2theta[rad] for the normalizer, which propagated to the esd.
